spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQL_DATABASE}?serverTimezone=UTC
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true  # SQL 포맷 정렬 여부
        highlight_sql: true  # SQL 하이라이트 여부
        use_sql_comments: true
        show-sql: true


  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_SECRET_KEY}
            scope:
              - account_email
              - profile_image
              - profile_nickname

            client-name: Kakao
            authorization-grant-type: authorization_code
            #redirect-uri: "https://plogging-buddy.vercel.app/oauth/callback/kakao"
            redirect-uri: "http://localhost:8080"
            client-authentication-method: client_secret_post


        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# 서버 포트 설정 (기본 포트 변경 시)
server:
  port: 8080
#  servlet:
#    context-path: /api/v1 # controller 접두사

# 로깅 레벨 설정 (필요 시)
logging:
  level:
    root: info
  


app:
  jwt:
    secret: ${JWT_SECRET_KEY}
  cors:
    front-path: "https://plogging-buddy.vercel.app"
